### ISSUE TITLE
Usage of a task runner e.g. gulp

### ISSUE THREAD

**Issue by softwarespot** [chrisdavies/plite#2]
Have you considered using the likes of gulp to minify, lint (ESLint) and test as well? I would be happy to submit a PR if you do.

**Comment by chrisdavies** [comment]
Absolutely! I use gulp at work all the time. The "lite" libraries that I've written were originally done as an experiment to see how small I could make them. I wonder if ESLint will complain at some of the tricks I used?

**Comment by softwarespot** [comment]
Well I work in a team who think it's pretty small =) So was wondering how I could contribute and came up with adding a build process + linting. My way of giving back.

**Comment by chrisdavies** [comment]
Sweet! I'd happily take your contributions.
